collections:
  - name: debops.debops
    version: "3.1.0"
  - name: devsec.hardening
    version: "9.0.1"
  - name: community.general
  - name: ansible.posix
roles:
  - name: geerlingguy.certbot
    version: "5.1.1"
  - name: geerlingguy.docker