collections:
  - name: debops.debops
    source: https://galaxy.ansible.com
    version: "3.0.3"
  - name: devsec.hardening
    source: https://galaxy.ansible.com
    version: "8.1.0"
  - name: community.general
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
roles:
  - name: geerlingguy.certbot
    version: "5.0.1"
